name: xeus-cpp-docs

channels:
  - conda-forge

dependencies:
  - breathe
  # Build dependencies
  - cmake
  # Host dependencies
  - cpp-argparse
  - xeus-zmq=1.0.2
  - xeus-dev
  - zeromq
  - nlohmann_json
  - cppzmq
  - xtl
  - pugixml
  - libllvm14
  - cxxopts
